### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by proukakis** [nygenome/lancet#10]
Hi I am getting this often. I guess it means that my mac just isn't up to the task.... It's funny though how it can run some bam files, and doesnt seem to depend on size (maybe the number of variants is what determines whether it runs?). Also, it seems to crash at different times when repeating the same analysis.

Anyway, Thought I would post in case you have any other ideas, otherwise will need to get onto our main server to use it.

The max is El capitan, single core, 16 Gb RAM only, 32Gb free disk space.

The command is ./lancet --tumor X --normal Y --ref Z --bed B -cov-thr 200 --max-alt-count-normal 5 --max-vaf-normal 0.1 > A. vcf. I have varied the options but doesnt seem to matter

thanks
christos

**Comment by gnarzisi** [comment]
Hi Christos,

depending on the amount of data, it is possible that 16GB RAM is not enough. Is the program using all the available RAM? Please try running it on a smaller region first (maybe just one of the regions of the BED file) to check if it still produces the segmentation fault error.

**Comment by proukakis** [comment]
thanks, we'll try again after the ASHG and get back to you

**Comment by gnarzisi** [comment]
Ok, sounds good. I'll close the ticket for now. Feel free to reopen if needed.
