### ISSUE TITLE
lancet missing RB1 mutation

### ISSUE THREAD

**Issue by crazyhottommy** [nygenome/lancet#12]
Hi,

I am working on whole exome data, and lancet missed an important RB1 mutation.
I feed the lancet with the exome capture bed files.
It looks like one needs to expand the region a bit in order for lancet to call the mutation.

RB1 exon1
```
13      48878048        48878185
```

This will miss the mutation

```bash
lancet --tumor 03indel_rln_recal_bam/Pa01_recur_rln_recal.bam --normal 03indel_rln_recal_bam/Pa01_wbc_rln_recal.bam --reg 13:48878040-48878185  --ref /scratch/genomic_med/apps/annot/bundle/human_g1k_v37_decoy.fasta
```

expand 100 bp both up and downstream of the exon

This finds the mutations.
```bash
lancet --tumor 03indel_rln_recal_bam/Pa01_recur_rln_recal.bam --normal 03indel_rln_recal_bam/Pa01_wbc_rln_recal.bam --reg 13:48877940-48878285  --ref /scratch/genomic_med/apps/annot/bundle/human_g1k_v37_decoy.fasta

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  B17042956985-KY290-2-WES        F17042956988-KY290-2-WES
13      48878151        .       C       T       198.967 PASS    SOMATIC;FETS=198.967;TYPE=snv;LEN=1;KMERSIZE=21;SB=13.9835      GT:AD:SR:SA:DP 0/0:75,0:38,37:0,0:75    0/1:16,39:8,8:9,30:55

```

I am aware that lancet is using local assembly so a larger window is needed, a previous issue by me https://github.com/nygenome/lancet/issues/11 .  May be it is good to point out in the documentation that one needs to expand the exome capture regions a bit (recommendation? 300bp on both ends?)

Thanks!
Tommy

**Comment by gnarzisi** [comment]
Thank you for the suggestion Tommy.

Yes, expanding of 300bp on both sides is recommended. I will include a command line option for it in the next release and update the documentation accordingly. 

I will close this ticket, but please share any other comment or suggestion in the future. Thanks!

**Comment by crazyhottommy** [comment]
great and thanks for this useful tool!

Thanks,
Tommy
