### ISSUE TITLE
Makefile Issue

### ISSUE THREAD

**Issue by adbhatt** [nygenome/lancet#13]
I receive the following error when running the make command on my local machine:
./Microassembler.hh:43:10: fatal error: 'api/BamReader.h' file not found
#include "api/BamReader.h"
         ^~~~~~~~~~~~~~~~~

**Comment by gnarzisi** [comment]
Please check that the Bamtools api has been correctly compiled. Note that it requires CMake to be installed in your system.

**Comment by gnarzisi** [comment]
Since there are no updates I'll close the ticket.
Feel free to reopen if your problem is still not solved.
