### ISSUE TITLE
problem with MAKE

### ISSUE THREAD

**Issue by haoziyeung** [nygenome/lancet#14]
hello there,i have error when make, can somebody help me ? thanks alot

mkdir /gpfs/users/yanghao/software/lancet/bamtools-2.3.0/build; cd /gpfs/users/yanghao/software/lancet/bamtools-2.3.0/build; cmake ..; make; cd ../../
mkdir: cannot create directory ‘/gpfs/users/yanghao/software/lancet/bamtools-2.3.0/build’: File exists
CMake Error at CMakeLists.txt:13 (cmake_policy):
  Policy "CMP0042" is not known to this version of CMake.

-- Configuring incomplete, errors occurred!
make[1]: Entering directory `/gpfs/users/yanghao/software/lancet/bamtools-2.3.0/build'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/gpfs/users/yanghao/software/lancet/bamtools-2.3.0/build'
cd /gpfs/users/yanghao/software/lancet/htslib-1.3; ./configure; make; cd ../
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ranlib... ranlib
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for gmtime_r... yes
checking for zlib.h... yes
checking for inflate in -lz... yes
configure: creating ./config.status
config.status: creating config.mk
config.status: creating config.h
config.status: config.h is unchanged
make[1]: Entering directory `/gpfs/users/yanghao/software/lancet/htslib-1.3'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/gpfs/users/yanghao/software/lancet/htslib-1.3'
cd src; make; cp lancet ../; cd ../
make[1]: Entering directory `/gpfs/users/yanghao/software/lancet/src'
g++ -std=c++0x -Wno-deprecated -Wall -O3 -fexceptions -g -Wl,-rpath,/gpfs/users/yanghao/software/lancet/bamtools-2.3.0/lib/ -I/gpfs/users/yanghao/software/lancet/bamtools-2.3.0/include/ -I/gpfs/users/yanghao/software/lancet/htslib-1.3/ -L/gpfs/users/yanghao/software/lancet/bamtools-2.3.0/lib/ -L/gpfs/users/yanghao/software/lancet/htslib-1.3/ Lancet.cc Edge.cc Node.cc Graph.cc Microassembler.cc Ref.cc Path.cc ContigLink.cc align.cc util.cc sha256.cc VariantDB.cc Variant.cc -o lancet /gpfs/users/yanghao/software/lancet/htslib-1.3/libhts.a -lz -ldl -lbamtools -lpthread
In file included from Lancet.hh:27:0,
                 from Lancet.cc:1:
Microassembler.hh:43:27: fatal error: api/BamReader.h: No such file or directory
 #include "api/BamReader.h"
                           ^
compilation terminated.
In file included from Microassembler.cc:1:0:
Microassembler.hh:43:27: fatal error: api/BamReader.h: No such file or directory
 #include "api/BamReader.h"
                           ^
compilation terminated.
In file included from Variant.hh:32:0,
                 from Variant.cc:1:
FET.hh: In member function ‘double Variant_t::compute_FET_score()’:
FET.hh:71:22: warning: ‘aux.FET_t::hgacc_t::n’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                      ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n’ was declared here
   hgacc_t aux;
           ^
FET.hh:71:31: warning: ‘aux.FET_t::hgacc_t::n1_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                               ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n1_’ was declared here
   hgacc_t aux;
           ^
FET.hh:71:15: warning: ‘aux.FET_t::hgacc_t::n_1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
               ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n_1’ was declared here
   hgacc_t aux;
           ^
FET.hh:72:25: warning: ‘aux.FET_t::hgacc_t::n11’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (n11 == aux->n11 + 1) { // incremental
                         ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n11’ was declared here
   hgacc_t aux;
           ^
FET.hh:74:69: warning: ‘aux.FET_t::hgacc_t::p’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       * (aux->n_1 - aux->n11) / (n11 + aux->n - aux->n1_ - aux->n_1);
                                                                     ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::p’ was declared here
   hgacc_t aux;
           ^
FET.hh: In member function ‘double Variant_t::compute_SB_score()’:
FET.hh:71:22: warning: ‘aux.FET_t::hgacc_t::n’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                      ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n’ was declared here
   hgacc_t aux;
           ^
FET.hh:71:31: warning: ‘aux.FET_t::hgacc_t::n1_’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                               ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n1_’ was declared here
   hgacc_t aux;
           ^
FET.hh:71:15: warning: ‘aux.FET_t::hgacc_t::n_1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
               ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n_1’ was declared here
   hgacc_t aux;
           ^
FET.hh:72:25: warning: ‘aux.FET_t::hgacc_t::n11’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (n11 == aux->n11 + 1) { // incremental
                         ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::n11’ was declared here
   hgacc_t aux;
           ^
FET.hh:74:69: warning: ‘aux.FET_t::hgacc_t::p’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       * (aux->n_1 - aux->n11) / (n11 + aux->n - aux->n1_ - aux->n_1);
                                                                     ^
FET.hh:95:11: note: ‘aux.FET_t::hgacc_t::p’ was declared here
   hgacc_t aux;
           ^
make[1]: *** [lancet] Error 1
make[1]: Leaving directory `/gpfs/users/yanghao/software/lancet/src'
cp: cannot stat ‘lancet’: No such file or directory

**Comment by gnarzisi** [comment]
This is likely due to using an old version of CMake. Can you try suing CMake >= 3.0 ?
