### ISSUE TITLE
Install fails. 

### ISSUE THREAD

**Issue by tstricker** [nygenome/lancet#15]
I am trying to install lancet and it fails with the following:

Lancet.cc:414: error: undefined reference to 'BamTools::BamReader::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

I am happy to send the entire log if necessary.  it is a CentOS6 cluster, tried with CMake/3.7.2 and  Intel/2016.3.210-GCC-5.4.0-2.26 and CMake/3.6.2 and GCC/5.4.0-2.26

**Comment by gnarzisi** [comment]
Yes, the entire log would be useful. It is possible that something else failed earlier during compilation.

**Comment by gnarzisi** [comment]
Couple of observations/questions: 

1. It seems that htslib was skipped during compilation, like it was already compiled (please double check). Here are the corresponding lines from your log file:

make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/gpfs22/home/strickt2/SEQanalysis/lancet/htslib-1.3'

2. In the README we recommend using GCC (version >= 4.8.x). I see in your log file that you are using 4.4.7:

-- The CXX compiler identification is GNU 4.4.7

Can you please install a more recent version of GCC and retry? We routinely compile the software with GCC v4.8.5 or v4.9.2 without problems.

**Comment by tstricker** [comment]
That seemes to have worked. Sorry, we have two package handlers we can use to define environments on our cluster, and the newer package handler has the older GCC versions for some reason.

**Comment by gnarzisi** [comment]
Glad it solved the problem. I will close the ticket, but feel free to report any other problem or bug in the future.
