### ISSUE TITLE
lancet fails to detect an obvious deletion, which it detected in a previous run

### ISSUE THREAD

**Issue by gilhornung** [nygenome/lancet#19]
Hi Giuseppe,

Following issue #16, I switched to bwa v0.7.15, which generates the MD tags. I was able to detect all mutations that I missed, but there is (at least) one peculiar case, in which lancet detected a variant in the previous run (bwa v0.7.5) but not in the current run (bwa v0.7.15). It is a very clear deletion, as you can see from the IGV image below. Any idea what is wrong? It is not the active regions, because I set it off.

Below are the commands to reproduce the issue. All the files can be found [in this link](https://owncloud.incpm.weizmann.ac.il/owncloud/index.php/s/HltGOlzT6wegHtp)

Thanks for the help,

Gil

```
# Running lancet of bam files which were aligned by bwa v0.7.15
isrv07:.../lancet_bug>../bin/lancet-1.0.5 -t tumor_LYZL1.bam \
	-n normal_LYZL1.bam \
	-r /bio/db/gendb/Homo_sapiens/Ensembl/GRCh38/sequence/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa \
	-p 10 --num-threads 12 \
	--active-region-off \
	> LYZL1_ar_off.vcf

isrv07:.../lancet_bug>grep PASS LYZL1_ar_off.vcf

isrv07:.../lancet_bug>

# Running lancet on bam files which were aligned by bwa v0.7.5 (older version, without MD tags)
isrv07:.../lancet_bug>../bin/lancet-1.0.5 -t tumor_LYZL1.bwa075.bam \
	-n normal_LYZL1.bwa075.bam \
	-r /bio/db/gendb/Homo_sapiens/Ensembl/GRCh38/sequence/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa \
	-p 10 --num-threads 12 \
	--active-region-off \
	> LYZL1_bwa075_ar_off.vcf
isrv07:.../lancet_bug>grep PASS LYZL1_bwa075_ar_off.vcf
10      29292661        .       CCATGTCGCCTGCT  C       160.756 PASS    SOMATIC;FETS=160.756;TYPE=del;LEN=13;KMERSIZE=15;SB=10.4582     GT:AD:SR:SA:DP  0/0:228,0:88,140:0,0:228  0/1:376,85:169,207:40,45:461	
```

![lyzl1_igv](https://user-images.githubusercontent.com/25452585/38871359-46b7afc2-4259-11e8-89ed-429d85ec42b5.png)

**Comment by gnarzisi** [comment]
Hi Gil,

glad that all your calls are found now! 

I inspected the alignments for this deletion and I found out that most the reads supporting the variant have the XA flag in your bwa v0.7.15 bam file. This generally means that the alignments are multi-mapped. Lancet currently skips multi-mapped alignments so this is the reason why your call is not reported with  bwa v0.7.15. However, what is strange is that the same set of alignments do not have the XA tag in your bwa v0.7.5 bam file (see example below) and based on the AS and XS tags these reads are not very repetitive. 

BWA v0.7.5:
`E00417:116:H7FJJCCXY:3:2121:14519:47281	1187	10	29292606	56	151M	=	29292632	177	AGATCAACAGCTTCGCGTGGTGCAGACGCGGAAAGCTGAAGGAGAACAACCACTGCCATGTCGCCTGCTCAGGTGAGGCTCTGACTTTCCAGTGATGCCATCCTCAGGACTAGGCAAGAAAGCCGACAATGGGATCAACAACCATGTCTTG	9977;;7<==?<<?:@);?:4>?7??>?@?>>,?:@;=???A,:,::??@;7@A>A?@1:>A=@@<AC9=>?:>>?,@C=A>>7;138A?9@>A?>@A@?>=<,=?AA<?>>B=B=?A<-8==73@6>/5/-?7+*@=:@?@??6?6<-5;	NM:i:2	AS:i:141	XS:i:126	RG:Z:GPS`

BWA v0.7.15:
`E00417:116:H7FJJCCXY:3:2121:14519:47281	163	10	29292606	60	151M	=	29292632	177	AGATCAACAGCTTCGCGTGGTGCAGACGCGGAAAGCTGAAGGAGAACAACCACTGCCATGTCGCCTGCTCAGGTGAGGCTCTGACTTTCCAGTGATGCCATCCTCAGGACTAGGCAAGAAAGCCGACAATGGGATCAACAACCATGTCTTG	9977;;7<==?<<?:@);?:4>?7??>?@?>>,?:@;=???A,:,::??@;7@A>A?@1:>A=@@<AC9=>?:>>?,@C=A>>7;138A?9@>A?>@A@?>=<,=?AA<?>>B=B=?A<-8==73@6>/5/-?7+*@=:@?@??6?6<-5;	NM:i:2	MD:Z:115G21C13	AS:i:141	XS:i:126	RG:Z:GPS	XA:Z:10,-30626026,151M,5;`

**Comment by gilhornung** [comment]
So it is an aligner issue... Thanks for looking at it!
