### ISSUE TITLE
Can we get a Bioconda package?

### ISSUE THREAD

**Issue by holtgrewe** [nygenome/lancet#2]
Installing lancet via [Bioconda](http://bioconda.github.io/index.html) would be nice but the license prohibits this.

**Comment by gnarzisi** [comment]
What type of license is needed? I am confident we can arrange it.

**Comment by holtgrewe** [comment]
I think it would be sufficient that we can redistribute as Bioconda packages, e.g., a written permission of some form, as given in Lancet's license file.

**Comment by gnarzisi** [comment]
Can you point me to the lancet license section that is currently blocking you?

**Comment by holtgrewe** [comment]
Yes, point 2.2. I think a written permission, e.g., in a ticket over at bioconda/bioconda-recipes would be enough.

**Comment by johanneskoester** [comment]
Funny, I just wanted to ask the same @holtgrewe :-).

**Comment by johanneskoester** [comment]
@gnarzisi any update on this? Would you be willing to express an exception of 2.2 for bioconda? If you want, I can open a ticket for you and you can simply post the exception at bioconda.

**Comment by johanneskoester** [comment]
Also, for bioconda it would be nice to have a true release of lancet with a version number (via the github release mechanism). Would that be possible?

**Comment by gnarzisi** [comment]
Done! Thank you for the suggestion.

**Comment by johanneskoester** [comment]
Great, thanks! Shall I prepare the consent regarding redistribution?

**Comment by gnarzisi** [comment]
Regarding 2.2, I am looking into modifying directly the license to allow redistribution by package managers such as Bioconda. However it needs to be first approved by our legal office. Sorry this is taking so long.

**Comment by johanneskoester** [comment]
Ok, thanks for working on this! Please let us know once you have a solution.

**Comment by johanneskoester** [comment]
@gnarzisi any update?

**Comment by johanneskoester** [comment]
@gnarzisi any update?

**Comment by gnarzisi** [comment]
No update yet, sorry.

**Comment by gnarzisi** [comment]
It looks like we are not going to change our license terms anytime soon. I am sorry. Closing the issue for know. I will reopen in the future if things change.
