### ISSUE TITLE
lancet reports a di-nucleotide variant as two single variants

### ISSUE THREAD

**Issue by gilhornung** [nygenome/lancet#20]
Hi Giuseppe,

I noticed a couple of cases where there is a di-nucleotide variant which is reported as two single-base variants. This is common in many variant callers, but I did not expect it to happen after the local assembly.

Below are the relevant lines from a VCF. bam files to reproduce it are `normal_CADPS2.bam` and `tumor_CADPS2.bam` from [this link](https://owncloud.incpm.weizmann.ac.il/owncloud/index.php/s/HltGOlzT6wegHtp)

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  dna_normal      dna_tumor
7       122387076       .       C       A       17.4654 PASS    SOMATIC;FETS=17.4654;TYPE=snv;LEN=1;KMERSIZE=13;SB=6.57933      GT:AD:SR:SA:DP  0/0:104,0:50,54:0,0:104 0/1:130,7:71,59:5,2:137
7       122387077       .       G       A       17.5928 PASS    SOMATIC;FETS=17.5928;TYPE=snv;LEN=1;KMERSIZE=13;SB=6.57933      GT:AD:SR:SA:DP  0/0:105,0:50,55:0,0:105 0/1:130,7:71,59:5,2:137
```

**Comment by gnarzisi** [comment]
Hi Gil,

yes, that is the correct behavior, for now. Variants (even if closely located) are not phased, but reported as separate entries in the output VCF.  We plan to add support for phasing in the future, but there is no timeline for when this will be implemented.

**Comment by gnarzisi** [comment]
The latest release now reports multiple consecutive variants as single events (via VCF replacement operations). Cheers!

**Comment by gilhornung** [comment]
Thanks!
