### ISSUE TITLE
lancet does not build (Centos 6.9, gcc gcc-4.9.3)

### ISSUE THREAD

**Issue by jbsysadmin** [nygenome/lancet#23]
We had a user request lancet. But it does not build on Centos.
Here is the crucial breakdown on a build attempt. Any leads?

-John B.
NYC

------------------------------ [edit] -----------------------------
make[1]: Entering directory `/usr/local/installs/lancet-master-1.0.3/htslib-1.8'
gcc -Wall -g -O2 -I.  -c -o kstring.o kstring.c
/tmp/ccCmAsG1.s: Assembler messages:
/tmp/ccCmAsG1.s:1392: Error: expecting string instruction after `rep'
/tmp/ccCmAsG1.s:1488: Error: expecting string instruction after `rep'
make[1]: *** [kstring.o] Error 1
make[1]: Leaving directory `/usr/local/installs/lancet-master-1.0.3/htslib-1.8'
cd src; make; cp lancet ../; cd ../
make[1]: Entering directory `/usr/local/installs/lancet-master-1.0.3/src'
g++ -std=c++0x -Wno-deprecated -Wall -O3 -fexceptions -g -Wl,-rpath,/usr/local/installs/lancet-master-1.0.3/bamtools-2.5.1/lib64/ -I/usr/local/installs/lancet-master-1.0.3/bamtools-2.5.1/include/bamtools -I/usr/local/installs/lancet-master-1.0.3/htslib-1.8/ -L/usr/local/installs/lancet-master-1.0.3/bamtools-2.5.1/lib64/ -L/usr/local/installs/lancet-master-1.0.3/htslib-1.8/ Lancet.cc Edge.cc Node.cc Graph.cc Microassembler.cc Ref.cc Path.cc ContigLink.cc align.cc util.cc sha256.cc VariantDB.cc Variant.cc -o lancet /usr/local/installs/lancet-master-1.0.3/htslib-1.8/libhts.a -llzma -lbz2 -lz -ldl -lpthread -lcurl -lcrypto -lbamtools
g++: error: /usr/local/installs/lancet-master-1.0.3/htslib-1.8/libhts.a: No such file or directory
make[1]: *** [lancet] Error 1
make[1]: Leaving directory `/usr/local/installs/lancet-master-1.0.3/src'
cp: cannot stat `lancet': No such file or directory

**Comment by gnarzisi** [comment]
It looks like the htslib library could not be compiled. Which is strange since it's widely used.

Please check if an old compiler was used. I successfully compiled the code under Centos using GCC (version >= 4.8.x)

**Comment by jbsysadmin** [comment]
Thank you for reply.

At the time of “make”, I had gcc-4.9.3 in my PATH.
Was there some other place this needed to be declared, during “make?”

**Comment by jbsysadmin** [comment]
This did not compile. And at the time of “make”, I had gcc-4.9.3 in my PATH. Was there some other place this version needed to be declared, during “make?”

**Comment by gnarzisi** [comment]
Based on your initial message, the error seems to appear when compiling one the of the htslib classes (kstring.c). Have you tried compiling htslib separately (https://github.com/samtools/htslib)? Can you share the full output of the compilation for lancet? You can attach it here as a txt file.

**Comment by gnarzisi** [comment]
That is strange. Yes, I would ask the htslib team directly. They may have encountered this problem before. It would be great if you could update this ticket once you find a solution. It would be useful for other users in the future. Thanks.

**Comment by jbsysadmin** [comment]
Htslib succeeded when use used in-OS gcc 4.4.7. I added the resulting bin and lib directories to PATH/LD_LIBRARY_PATH.

However, when I try to build lancet with gcc 4.9.3, your build process insists on rebuilding Htslib, instead of using the one built on 4.4.7. Log enclosed.

Please advise.
-John

From: Burns, W. J.
Sent: Friday, July 13, 2018 4:25 PM
To: 'nygenome/lancet' <reply@reply.github.com>; nygenome/lancet <lancet@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [nygenome/lancet] lancet does not build (Centos 6.9, gcc gcc-4.9.3) (#23)

Sadly, htslib “make” compilation fails on:

gcc -Wall -g -O2 -I.  -c -o kfunc.o kfunc.c
gcc -Wall -g -O2 -I.  -c -o knetfile.o knetfile.c
gcc -Wall -g -O2 -I.  -c -o kstring.o kstring.c
/tmp/ccptG2m8.s: Assembler messages:
/tmp/ccptG2m8.s:1392: Error: expecting string instruction after `rep'
/tmp/ccptG2m8.s:1488: Error: expecting string instruction after `rep'
make: *** [kstring.o] Error

I guess I need to ask those folks why their item doesn’t build...

-John

**Comment by gnarzisi** [comment]
Have you tried compiling the whole lancet source code using gcc 4.4.7 ? It should work.

**Comment by jbsysadmin** [comment]
I did not, because I think your site lists a newer gcc as a pre-req.

This build still failed. I caught where things broke down, and enclosed here....

**Comment by gnarzisi** [comment]
This time it seems the problem is that BamTools is not compiled properly:

`Microassembler.hh:43:27: error: api/BamReader.h: No such file or directory`

Can you check if CMake produced an error?

**Comment by gnarzisi** [comment]
The error now is:

> /nfs/goldstein/software/binutils-2.26.1/bin/ld: /tmp/ccnMOotb.o: undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'
> /lib64/librt.so.1: error adding symbols: DSO missing from command line

This [post](https://github.com/Bumblebee-Project/Bumblebee/issues/76) seems to suggest that adding -lrt to the compiler option could solve the problem. Can you give it a try? The variable is LDLIBS and the relevant Makefile is: https://github.com/nygenome/lancet/blob/master/src/Makefile

**Comment by gnarzisi** [comment]
Any update on this? I will close the ticket for now, but feel free to reopen if you have more questions.

**Comment by jbsysadmin** [comment]
I spotted your latest 1.0.7, then tried again. Same error on make:

-John

[edit]

/binutils-2.26.1/bin/ld: /tmp/ccCDcMvB.o: undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'
/lib64/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [lancet] Error 1
make[1]: Leaving directory `/usr/local/installs/lancet-1.0.7/src'
cp: cannot stat `lancet': No such file or directory
