### ISSUE TITLE
Is bed file required for WES data?

### ISSUE THREAD

**Issue by snoopy-448** [nygenome/lancet#24]
Hi,
I want to find somatic mutations from my WES data using LANCET. I noted that --bed is a required argument, but I can still run LANCET without bed file. So I want to know what the difference between providing a bed file and not providing a bed file. Will providing bed file improve the accuracy of LANCET or just improve its speed?
Thanks!

Yang

**Comment by gnarzisi** [comment]
Can you please share the command line that you use? The --bed option is a required parameter. so  lancet should not be able to run without it and it should output the following error message:

> ERROR: Must provide region (-p) or BED file (-B)

**Comment by snoopy-448** [comment]
Oh, I use the region parameter, --reg 1:1-249250621. But I input the whole chromosome, not just the exome region. So I wonder if it is reasonable for WES data. Would BED file for exome be better than whole chromosome?

**Comment by gnarzisi** [comment]
I would recommend using only the exome regions (with the --bed option) for WES, except if you are doing something special and you want to call also within regions of the genome that should not have been captured (assuming you know that there is sequencing data mapped in these regions too).

**Comment by snoopy-448** [comment]
Thanks!
