### ISSUE TITLE
Memory and Runtime

### ISSUE THREAD

**Issue by ahwanpandey** [nygenome/lancet#26]
First off thanks for this awesome tool!

I just discovered Lancet a couple of days ago and have been testing it on some WGS data. I have 48 Tumor/Normal pairs to run, with a lot more data incoming soon. Before I invested too much time on it I was going to do some benchmarking with some results from other tools we have already run. Also wanted to get an idea of how realistic it would be to run Lancet on such a large cohort given the computing resources I have. By default a user is capped at 90 CPUs at one time. Also priority comes into effect and sometimes when the cluster is full I only see about 5 to 10 cores free per user! Memory limits are no issue as long as they are realistic. I decided to split every chromosome into 3 regions. Sure I could split the larger chromosomes into more regions and smaller into lesser, but just wanted to keep it simple in this fist test.

The command is:
`lancet --tumor tumor.recal.bam --normal normal.recal.bam --ref human_g1k_v37.fasta --bed regA.chrB.bed --num-threads 8`

where (regA) goes from (1-72) and chrB goes from (1 to 22, X, MT). So a total of 72 jobs per sample with each job requesting 30GB and 8 threads.

The average coverage for the Normals is 40x and the Tumors is 80x

I have attached run-times of thread 1 for each of the jobs as I figured the run-times are similar between threads. Keep in mind the best case scenario for jobs running concurrently is 11 jobs requesting 8 threads each (i.e. 88 cores being used).

```
REGION_ID	CHROMOSOME	Elapsed time thread1 (hrs)
reg1	1	7.289777778
reg2	1	8.385305556
reg3	1	6.514277778
reg4	2	6.756916667
reg5	2	8.549111111
reg6	2	6.455666667
reg7	3	7.225888889
reg8	3	7.361805556
reg9	3	5.463055556
reg10	4	5.154444444
reg11	4	4.030166667
reg12	4	4.335027778
reg13	5	6.024444444
reg14	5	5.115027778
reg15	5	3.2065
reg16	6	3.953527778
reg17	6	4.191166667
reg18	6	2.476222222
reg19	7	3.918833333
reg20	7	6.621472222
reg21	7	4.082888889
reg22	8	2.602305556
reg23	8	4.359805556
reg24	8	6.478555556
reg25	9	4.088416667
reg26	9	3.244722222
reg27	9	4.872333333
reg28	10	4.01575
reg29	10	4.222555556
reg30	10	3.842694444
reg31	11	3.968222222
reg32	11	5.392555556
reg33	11	3.807027778
reg34	12	3.341333333
reg35	12	3.666388889
reg36	12	2.968
reg37	13	1.375472222
reg38	13	1.923166667
reg39	13	3.390722222
reg40	14	0.786972222
reg42	14	3.648527778
reg41	14	2.286166667
reg43	15	1.382638889
reg45	15	4.857083333
reg44	15	3.673861111
reg46	16	2.563305556
reg47	16	Job 2073292 exceeded memory limit (33390852 > 31457280), being killed
reg48	16	2.042722222
reg49	17	2.158833333
reg50	17	1.934472222
reg53	18	1.70975
reg51	17	4.275583333
reg52	18	2.026027778
reg54	18	1.588333333
reg55	19	2.4165
reg56	19	2.266583333
reg57	19	1.99225
reg58	20	2.809472222
reg59	20	3.324027778
reg60	20	3.095194444
reg61	21	1.828555556
reg62	21	1.537527778
reg63	21	1.732916667
reg64	22	0.128027778
reg65	22	1.549305556
reg66	22	1.066
reg67	X	3.484638889
reg68	X	3.24825
reg69	X	2.181777778
reg70	MT	0.022638889
reg71	MT	0.022611111
reg72	MT	0.02425
```

**Question1** -> do these run-times look realistic to you? Can I improve on them without straying too far from the optimized variant calling defaults of lancet?

**Question2** -> One of the regions (reg47) failed and said `[Job 2073292 exceeded memory limit (33390852 > 31457280), being killed]`. So it seems I would have to use more than 30GB per job just to be on the safe side. I am just arbitrarily testing memory required because on my first run I was only requesting 10GB and most jobs failed. So decided to try 30GB. How should I approach the memory requirements?

Really appreciate your feedback here.

**Comment by gnarzisi** [comment]
Thank you for the kind words! 
Here are my answers to your questions:

1. The running times that you listed are realistic for the 80x/30x tumor/normal coverage of your data. I am afraid you cannot improve them further without additional splitting of the regions or optimization of Lancet parameters. We plan to optimize the computational requirements in the future releases, but there is not timeline for it yet.

2. To be safe, you may want to allocate more memory to each job. In my testings I have rarely seen more than 60GB of usage for each job though.  

Thank your for sharing your benchmarking results.  Let me know if you have more questions.

**Comment by ahwanpandey** [comment]
Thanks for the input! Co-incidentally, I reran reg47 with 60GB and it is complete now.

I will definitely keep an eye out for any announcements regarding improved runtimes :)

**Comment by gnarzisi** [comment]
Great. I will close the ticket for now.

**Comment by wangjiawen2013** [comment]
I want to try Lancet now, but the running time in the first lancet paper scared me. Now two years have past, Is the running time improved now ?

**Comment by gnarzisi** [comment]
Minor improvements in speed where implemented over the years. Major refactoring of the code, with substantial speedup, is underway, but to be released later next year.
