### ISSUE TITLE
Any guidance for faster running times

### ISSUE THREAD

**Issue by messersc** [nygenome/lancet#3]
Hi @gnarzisi,

we are currently running lancet on a cohort of matched tumor/normal WGS samples. To do that, we split the jobs per chromosome, but the largest chromosomes still take a lot of time to compute.

Therefore, I would like to ask if you could give us some sensible advise on how to cut down running time without giving up to much in terms of sensitivity. More memory consumption would also be fine.

Cheers,
Clemens

**Comment by gnarzisi** [comment]
Hi Clemens,

How long does it take for you to process the larges chromosome?
How many threads are you using (with the --num-threads option) ? I recommend using at at least 8 (if you have the computational resources).

One way you should be able to reduce the running time is by increasing the low coverage threshold (default 1) to 2 or more. However, depending on the average coverage of your data, larger values may have a strong impact on sensitivity of low variant allele fraction mutations.

**Comment by messersc** [comment]
Hi Giuseppe,

thanks for getting back to me. From the logs, the jobs for chr 1 seem to run ~300000 seconds, so 3.5 days wall clock time. Is this unexpectedly slow?

Right now, each lancet job gets 8 threads, although monitoring some jobs with htop it looks like it seldom goes over 300% CPU, so 3-4 threads might be enough...

Thanks for the hint about setting the low coverage threshold, I was thinking about this but was unsure about performance impact. I will look into this later and report back.

In the meantime, what is your strategy/best practice when running lancet? Do you also run it per chromosome or does it make sense to run it on smaller windows? This would of course enable better parallelization, but while it seems save for SNVs, Indels spanning window borders would lead to funny calls.

**Comment by gnarzisi** [comment]
3.5 days sounds too slow for chr1.
Also it is suspicious that you have only 300% CPU if you run lancet with 8 threads (you show have 800% CPU performance). 

You can also split hg19/GRCh37 chr1 in two regions at the Ns:

reg1=1:1-149484645
reg2=1:149484645-249250621

**Comment by gnarzisi** [comment]
@messersc, just checking if you are still facing slow running time or if you have adopted any particular solution. Thanks.

**Comment by messersc** [comment]
Hi,

I liked your suggestions about splitting the genome at polyN gaps, which reduces wall clock time quite a bit due to better degree of parallelization. I am still not sure why lancet does not use 100% of the resources given, but for now it's ok.

**Comment by kmhernan** [comment]
@gnarzisi just wanting to pop in here cause this is a real issue for us with 1000's of WGS pairs and running on AWS it is possibly too expensive splitting by chromosomes. We haven't tested splitting by N yet, but didn't know if you had any suggestions in other window sizes.

**Comment by gnarzisi** [comment]
Hi Kyle I hear you. 1000 WGS pairs is a substantial amount of data!

At this time, Lancet is more computationally intese than other somatic variant caller. Something that we plan to address in the future releases. For now, splitting by Ns is what I would recommend as well. We did not explore the effect of different window sizes on running time. Increasing the size should not reduce the running time though. Sorry I cannot help you more at this time!

**Comment by wangjiawen2013** [comment]
How long will it take to run 10 WGS pairs now on a 64-core Centos7 system (200G memory)?

**Comment by gnarzisi** [comment]
Impossible to give an accurate estimate. It depends on multiple things: file system, hardware configuration, amount of data (e.g., average coverage of the tumor and normal samples), read length, etc. Generally speaking, speedup scales linearly with the number of parallel jobs/cores. We recommend processing each chromosome separately in parallel.

**Comment by wangjiawen2013** [comment]
It took about 20 hours per sample in this case. Faster than expected and it's acceptable for me. great !

**Comment by gnarzisi** [comment]
Great to hear!
