### ISSUE TITLE
util.cc:423: void parseMD(std::string&, std::map<int, int>&, int, std::string&, int): Assertion `rpos <= qual.length()' failed.

### ISSUE THREAD

**Issue by gilhornung** [nygenome/lancet#32]
Hi Giuseppe,

I am getting the following error when trying to run the new lancet version (1.0.7):
```
../bin/lancet-1.0.7 --tumor mutant.bam --normal wt.bam --ref /bio/db/gendb/Arabidopsis_thaliana/Ensembel/TAIR10/sequence/Arabidopsis_thaliana.TAIR10.dna_sm.toplevel.fa --reg 1
304272 total windows to process

starting thread 1 on 304272 windows
Process reads
lancet: util.cc:423: void parseMD(std::string&, std::map<int, int>&, int, std::string&, int): Assertion `rpos <= qual.length()' failed.
Aborted (core dumped)
```

You can find file to replicate the issue in the link below:
https://owncloud.incpm.weizmann.ac.il/owncloud/index.php/s/Qc9kdytLsrSQ7gN

Thanks!

Gil

**Comment by gnarzisi** [comment]
I did not check your data yet, but based on the assertion error, it seems that the quality string is of different length compared to the read sequence...

**Comment by gnarzisi** [comment]
Is the length of the quality string different than the sequence string? If yes, the BAM/SAM is malformed and the most recent lancet is then correct in reporting an error.

**Comment by gilhornung** [comment]
The length is the same:
```
samtools view mutant.bam | awk 'length($10)!=length($11){print}'

samtools view wt.bam | awk 'length($10)!=length($11){print}'
```

**Comment by gnarzisi** [comment]
Thanks for checking. Possibly a bug in the code then. I will take a look but it will not happen for the next few weeks.

**Comment by gnarzisi** [comment]
The reason for the error is that your BAM file contains alignments with undefined sequence or qualities. For example:

`NB501540:91:HTKJNBGX7:2:11210:20418:18379	433	1	1063	0	37H35M79H	3	1960406	0	*	*	NM:i:1	MD:Z:12T22	AS:i:30	RG:Z:Z46`

I pushed a fix to the repo. Just clone the most recent code and everything should work. 

Thank you for your patience.

**Comment by gilhornung** [comment]
Thanks for solving this!
