### ISSUE TITLE
Question regarding --XA-tag-filter option in lancet v1.0.7

### ISSUE THREAD

**Issue by gilhornung** [nygenome/lancet#33]
Hi Giuseppe,

I noticed that there is a new option in v1.0.7 ` --XA-tag-filter`, which tells lancet to skip reads with multiple hits listed in the XA tag. Skipping reads with multiple hits in XA tag was the default behaviour in v1.0.5. right? If I want to have this functionality I need to turn this option on?

Thanks,

Gil

**Comment by gnarzisi** [comment]
Yes, it was the default behavior before. Most likely you will not need to use this option since this tag seems to be obsolete in the more recent BWA aligner.

FYI, this is not part of the last release and it was introduced to fix an issue when using the iontorrent aligner (see #27).
