### ISSUE TITLE
Germline variants from lancet

### ISSUE THREAD

**Issue by gilhornung** [nygenome/lancet#34]
One last question regarding lancet...
Can I use the output in the VCF to extract germline variants (e.g. variants labelled `HighVafNormal;HighAltCntNormal`) or should I run another germline variant caller in parallel (e.g. HaplotypeCaller)? It seems to me that there shouldn't be a reason why to perform local assembly twice, but maybe I am missing something...

Thanks,

Gil

**Comment by gnarzisi** [comment]
Yes, you can use the germline variants reported by lancet. However, keep in mind that those are flagged as germline even when supported only by very few reads in the nromal (see default values for `HighVafNormal`, `HighAltCntNormal`, etc.)
