### ISSUE TITLE
Lancet won't use cmake3, although it is required

### ISSUE THREAD

**Issue by jbsysadmin** [nygenome/lancet#35]
Greetings. Prior sucessful builds of lancet involved specifying PATH to a custom build of cmake3. 
However, cmake does not build when we install 3.12.1-1.el7 by yum. (Specifically: yum install cmake3.x86_64)

When I try to compile this, I get error "CMake 3.0 or higher is required.  You are running version 2.8.12.2"
What needs to happen so that your build process sees an in-OS cmake3 ? ( Yum installs that in universal  PATH, /usr/bin/ccmake3.)

Note: the new compilation context is re-building this as an RPM. We have a directive to move away from non-RPM builds.

**Comment by gnarzisi** [comment]
Since specifying the path to cmake worked in the past. Can you specify the new path to the Yum cmake installation? Otherwise you could try creating a new "cmake" symlink to ccmake3. My guess is that the configure script looks for a "cmake" binary and cannot find it in the universal path.

**Comment by jbsysadmin** [comment]
We may not create RPMS resulting in disruptive changes to main system items. Yum install of the distro package puts cmake3 in /usr/bin, same place as cmake (2.x) Lancet build worked in past because we built cmake from source, then pre-empted use of cmake 2.x with a PATH.

That won’t be possible here, we need to work within the constraints of the provided cmake3. The lancet build instructions simply call for a “make.” I don’t see in MakeFile or that README a reference to cmake. I’m wondering what can be changed to reference /usr/bin/cmake3.

-John

**Comment by gnarzisi** [comment]
Lancet specific source code does not require cmake for compilation. CMake is needed to compile the bamtools API which is included in the lancet distribution: https://github.com/pezmaster31/bamtools/wiki/Building-and-installing 

I would recommend asking for support directly to the bamtools developers.

**Comment by jbsysadmin** [comment]
I was looking at the wrong makefile, “lancet-master/src/Makefile.”

Another file has an actual call to cmake, “lancet-master/Makefile”
I’ll start from there.

Systems admins may see the whole build proceess being under one product. The lancet build process fails because of a dependency requirement, but we contact the lancet support.

Thanks for your time,
-John
