### ISSUE TITLE
util.cc:423: void parseMD(std::string&, std::map<int, int>&, int, std::string&, int): Assertion `rpos <= qual.length()' failed.

### ISSUE THREAD

**Issue by Elizabeth237** [nygenome/lancet#36]
Hi Giuseppe,
When I ran the lancet (1.0.7), I have got a error:
![image](https://user-images.githubusercontent.com/44385901/47415276-a43f7d00-d7a5-11e8-801c-a69a4ea5449d.png)
After checking the data carefully, I found some of the following five reads cause  the error:
![image](https://user-images.githubusercontent.com/44385901/47416568-95a69500-d7a8-11e8-9d76-c297e635b319.png)
![image](https://user-images.githubusercontent.com/44385901/47416645-b7a01780-d7a8-11e8-9869-eeeb24edc0ab.png)
I cannot find the exact reads which cause this issue, but I have tried my best to narrow the range into these five reads. 

Thanks!
Liz

**Comment by Elizabeth237** [comment]
I have cloned the most recent code, but I still got this error. And these five reads do not look like undefined sequences or qualities~~~~~~

**Comment by Elizabeth237** [comment]
and I also checked the length of these sequences. The length of sequences and qualities are same, but in the second picture, the value of MD is longer than 150 and it also marks the missing('^').

**Comment by Elizabeth237** [comment]
I have found the reason:  bwa-mem may have different meaning in deletion and insertion. 
thx

**Comment by gnarzisi** [comment]
That is correct. Insertions are not represented in the MD string, only deletions. See the following page for more info: https://github.com/vsbuffalo/devnotes/wiki/The-MD-Tag-in-BAM-Files

If you share a small bam centered around the position causing the error, I should be able to reproduce your error and possibly provide a fix for it.

For the time being, you can avoid lancet looking at the MD string just by turning off the active-region module:

`--active-region-off, -W       : turn off active region module`

**Comment by Elizabeth237** [comment]
[small_bam.zip](https://github.com/nygenome/lancet/files/2518171/small_bam.zip)
thx, I have shared small_bam above. The file, called small_T.bam, contains the reads ("K00133:11:H2T3NBBXX:5:2227:20153:31027" and "K00133:11:H2T3NBBXX:5:2123:25938:3074") that may cause the error.
And another question: will the result be affected, when I turn off the active-region module?
thx! 
Liz

**Comment by gnarzisi** [comment]
Thank you for sharing the small bam.

Turning off the active region module should not affect the results. It is used to skip region/windows where there is not enough evidence (from the alignments) for mutations.

**Comment by gnarzisi** [comment]
I just pushed a fix to the repo.
There was a bug in the code that did not allow for lower-case basepairs in the MD string. 
Everything should be fine now. Please clone the most recent version of the code.
