### ISSUE TITLE
v 1.0.7 not compiling on Mac

### ISSUE THREAD

**Issue by proukakis** [nygenome/lancet#37]
hi, still using OS El Capitan- I had problems before with 16 Gb RAM, having more helps

v_1.0.6 works fine, so not bothered- posting in case it helps others

i do
make CC=gcc-6 CXX=g++-6

seems OK until here

Microassembler.cc: In member function 'int Microassembler::processReads()':
Microassembler.cc:644:16: error: 'CLOCK_MONOTONIC' was not declared in this scope
  clock_gettime(CLOCK_MONOTONIC, &start);
                ^~~~~~~~~~~~~~~
Microassembler.cc:644:39: error: 'clock_gettime' was not declared in this scope
  clock_gettime(CLOCK_MONOTONIC, &start);
                                       ^
In file included from Variant.hh:36:0,
                 from Variant.cc:1:
FET.hh: In member function 'double Variant_t::compute_FET_score()':
FET.hh:71:22: warning: 'aux.FET_t::hgacc_t::n' may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                  ~~~~^~~~~~~~
FET.hh:95:11: note: 'aux.FET_t::hgacc_t::n' was declared here
   hgacc_t aux;
           ^~~
FET.hh:71:31: warning: 'aux.FET_t::hgacc_t::n1_' may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                  ~~~~~~~~~~~~~^~~~~~~~~~
FET.hh:95:11: note: 'aux.FET_t::hgacc_t::n1_' was declared here
   hgacc_t aux;
           ^~~
FET.hh:71:15: warning: 'aux.FET_t::hgacc_t::n_1' may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
        ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
FET.hh:95:11: note: 'aux.FET_t::hgacc_t::n_1' was declared here
   hgacc_t aux;
           ^~~
FET.hh:72:25: warning: 'aux.FET_t::hgacc_t::n11' may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (n11 == aux->n11 + 1) { // incremental
                ~~~~~~~~~^~~
FET.hh:95:11: note: 'aux.FET_t::hgacc_t::n11' was declared here
   hgacc_t aux;
           ^~~
FET.hh:74:68: warning: 'aux.FET_t::hgacc_t::p' may be used uninitialized in this function [-Wmaybe-uninitialized]
       * (aux->n_1 - aux->n11) / (n11 + aux->n - aux->n1_ - aux->n_1);
                                                                    ^
FET.hh:95:11: note: 'aux.FET_t::hgacc_t::p' was declared here
   hgacc_t aux;
           ^~~
FET.hh: In member function 'double Variant_t::compute_SB_score()':
FET.hh:71:22: warning: 'aux.FET_t::hgacc_t::n' may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                  ~~~~^~~~~~~~
FET.hh:95:11: note: 'aux.FET_t::hgacc_t::n' was declared here
   hgacc_t aux;
           ^~~
FET.hh:71:31: warning: 'aux.FET_t::hgacc_t::n1_' may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
                  ~~~~~~~~~~~~~^~~~~~~~~~
FET.hh:95:11: note: 'aux.FET_t::hgacc_t::n1_' was declared here
   hgacc_t aux;
           ^~~
FET.hh:71:15: warning: 'aux.FET_t::hgacc_t::n_1' may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (n11%11 && n11 + aux->n - aux->n1_ - aux->n_1) {
        ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
FET.hh:95:11: note: 'aux.FET_t::hgacc_t::n_1' was declared here
   hgacc_t aux;
           ^~~
FET.hh:72:25: warning: 'aux.FET_t::hgacc_t::n11' may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (n11 == aux->n11 + 1) { // incremental
                ~~~~~~~~~^~~
FET.hh:95:11: note: 'aux.FET_t::hgacc_t::n11' was declared here
   hgacc_t aux;
           ^~~
FET.hh:74:68: warning: 'aux.FET_t::hgacc_t::p' may be used uninitialized in this function [-Wmaybe-uninitialized]
       * (aux->n_1 - aux->n11) / (n11 + aux->n - aux->n1_ - aux->n_1);
                                                                    ^
FET.hh:95:11: note: 'aux.FET_t::hgacc_t::p' was declared here
   hgacc_t aux;
           ^~~
make[1]: *** [lancet] Error 1
cp: lancet: No such file or directory

**Comment by gnarzisi** [comment]
It seems like "clock_gettime()" is not available in macOS before Sierra. The link below provides a possible solution. Hope it helps.

https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x

**Comment by proukakis** [comment]
thanks, will use 1.0.6 for now I think
