### ISSUE TITLE
Error: not able to jump successfully to the region's left boundary in tumor

### ISSUE THREAD

**Issue by toedling** [nygenome/lancet#38]
Hello,
I am trying to run lancet (v1.0.7) on a pair of tumor/normal BAM files which were generated by aligning whole-genome seq data using "bwa mem". The BAM files are OK, all other tools that I checked work fine with them. Chromosomes are named "chr1...chrX".

When running the following command
lancet --tumor $TUMORBAM --normal $CONTROLBAM --ref $GENOMEFA \
--reg chr1 --num-threads 1 >chr1.vcf

I get this error message

starting thread 1 on 2489560 windows
Process reads
Error: not able to jump successfully to the region's left boundary in tumor

Do you have any idea how that error might arise and how I could avoid it?
Thanks in advance.

**Comment by gnarzisi** [comment]
Are the chromosome labels in the reference genome FASTA file matching with the BAM?

**Comment by toedling** [comment]
Yes, the chromosome labels are the same. In this case I had used --reg chr1, and "chr1" is the label used for the first chromosome both in the BAM files and in the genome Fasta file.

**Comment by gnarzisi** [comment]
Thanks for checking. 

Can you reproduce the error using small BAMs extracted from the tumor and the normal? If you can share them with me, together with the reference used to aligned the data, I will be able to debug the problem on my side.

**Comment by gnarzisi** [comment]
Closing the ticket, but feel free to reopen if you still haven't solved your issue.
