### ISSUE TITLE
config.txt showing up in pwd

### ISSUE THREAD

**Issue by ryanrichholt** [nygenome/lancet#41]
I'm running lancet in a batched mode very similar to the "Genome-wide scan" example in the readme. After the jobs are done, I find a file `config.txt` in the pwd where I launched the command from. It does not appear to cause any conflicts with the individual jobs, each chunk comes out alright. But, is there any way to stop this file from being created? Thanks!

**Comment by gnarzisi** [comment]
Hi Ryan. Thank you for your feedback. I can see how the config file could be annoying if it is generated all the time. I added a new option flag (`--print-config-file`) to explicitly request the config file to be written out to file (turned off by default). To use this feature you have to pull the most recent code from the git repo. Cheers!

**Comment by ryanrichholt** [comment]
So fast! Thanks 👍

**Comment by yeemey** [comment]
Hello,
Is the  `--print-config-file` flag still implemented in the latest version? I cloned the repo last week, and noticed that the config.txt file is created. I'd actually like to specify where the config file gets created, if possible. Thank you!

**Comment by gnarzisi** [comment]
The `--print-config-file` flag is back now. Somehow it got lost in between releases...
