### ISSUE TITLE
Run lancet on Whole exome

### ISSUE THREAD

**Issue by medcelerate** [nygenome/lancet#43]
is there a method to bypass the --reg flag and have lancet run across the entire genome. We are doing this for workflow testing purposes and need only to spin up one process to execute.

**Comment by gnarzisi** [comment]
It is not possible to bypass both the `--reg`  and `--bed` options at this time. But you can achieve your goal by only using the `--bed` option and provide a BED file with the list of chromosomes/regions to analyze.

**Comment by medcelerate** [comment]
I have done that but I get an error from the argument handler. I can add
the exact error but it is from stdio

**Comment by gnarzisi** [comment]
Sharing the exact error would be useful.

**Comment by medcelerate** [comment]
erminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi

**Comment by medcelerate** [comment]
This is the command 
```
lancet --bed '/cromwell_root/cromwell-execution/cwl_temp_file_98f193c0-9ecc-4cad-902e-bd8598a13963.cwl/98f193c0-9ecc-4cad-902e-bd8598a13963/call-Lancet/inputs/602152829/S31285117_Covered.bed' '--normal' '/cromwell_root/cromwell-execution/cwl_temp_file_98f193c0-9ecc-4cad-902e-bd8598a13963.cwl/98f193c0-9ecc-4cad-902e-bd8598a13963/call-Lancet/inputs/726713051/normal_fixed_header.bam' '--ref' '/cromwell_root/cromwell-execution/cwl_temp_file_98f193c0-9ecc-4cad-902e-bd8598a13963.cwl/98f193c0-9ecc-4cad-902e-bd8598a13963/call-Lancet/inputs/79934331/GRCh38.primary_assembly.genome.fa' '--tumor' '/cromwell_root/cromwell-execution/cwl_temp_file_98f193c0-9ecc-4cad-902e-bd8598a13963.cwl/98f193c0-9ecc-4cad-902e-bd8598a13963/call-Lancet/inputs/726713051/tumor_grch38_17.bam'
```

**Comment by gnarzisi** [comment]
Why do you put the option names with `' '` (for examples` '--normal'`)?

**Comment by medcelerate** [comment]
It’s the way our job runner handles it. Even if I run the command without
‘’ it still produces the same error

**Comment by gnarzisi** [comment]
OK, but it is not consistent in your command, for example `--bed` does not have them. This got me confused about the syntax...

**Comment by medcelerate** [comment]
I removed some when I was copying my mistake.

**Comment by gnarzisi** [comment]
Anyway, the problem seems to be due to how your job runner interprets the command. I suggest you to run lancet outside of your job runner to test that the `--bed` option works correctly.

**Comment by medcelerate** [comment]
I did test running normally and encounter the same issue. The commands in
the same order.

**Comment by gnarzisi** [comment]
OK. So my next guess is to look into the format of the BED file that you provide. Can you please check that the chromosome labels are the same as the used used in the BAM file? Same for the reference file? Are the header lines properly commented out (with `#`)?

**Comment by medcelerate** [comment]
Yes they are the same

**Comment by medcelerate** [comment]
Ran this command and got the same issue.

```
lancet --bed /cromwell_root/cromwell-execution/cwl_temp_file_98f193c0-9ecc-4cad-902e-bd8598a13963.cwl/98f193c0-9ecc-4cad-902e-bd8598a13963/call-Lancet/inputs/602152829/S31285117_Covered.bed --tumor /cromwell_root/cromwell-execution/cwl_temp_file_98f193c0-9ecc-4cad-902e-bd8598a13963.cwl/98f193c0-9ecc-4cad-902e-bd8598a13963/call-Lancet/inputs/726713051/tumor_grch38_17.bam --normal /cromwell_root/cromwell-execution/cwl_temp_file_98f193c0-9ecc-4cad-902e-bd8598a13963.cwl/98f193c0-9ecc-4cad-902e-bd8598a13963/call-Lancet/inputs/726713051/normal_fixed_header.bam --ref /cromwell_root/cromwell-execution/cwl_temp_file_98f193c0-9ecc-4cad-902e-bd8598a13963.cwl/98f193c0-9ecc-4cad-902e-bd8598a13963/call-Lancet/inputs/79934331/GRCh38.primary_assembly.genome.fa
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
```

**Comment by gnarzisi** [comment]
If possible, can you share the BED file and a portion of the tumor and normal BAM files so that I can try to reproduce your error on my side?

**Comment by medcelerate** [comment]
Yes I can, what is the email I can best reach you at.

**Comment by gnarzisi** [comment]
If not too big, you should be able to attach it directly here (drag and drop).

**Comment by medcelerate** [comment]
The files are sizeable

**Comment by gnarzisi** [comment]
Please do not share very large files. I only need a very small portion of the BAMs (together with the BED) that you have tested on your side to reproduce the same error.

**Comment by medcelerate** [comment]
Ok I will filter the bam, here is the bed file.
[S31285117_Covered.bed.zip](https://github.com/nygenome/lancet/files/3790402/S31285117_Covered.bed.zip)

**Comment by medcelerate** [comment]
[files.zip](https://github.com/nygenome/lancet/files/3790524/files.zip)
Here are the rest of the files

**Comment by gnarzisi** [comment]
The header lines of your BED file needed to be commented out with `#`. After doing so I was able to successfully run Lancet on your tumor/normal pair with the following command:

```
lancet \
    --tumor tumor_small.bam \
    --normal normal_small.bam \
    --ref GRCh38.fa \
    --bed S31285117_Covered.bed
```

**Comment by wangjiawen2013** [comment]
For both germline and somatic analysis, Strelka may have runtime issues while attempting to process the large number of small decoys and unplaced/unlocalized contigs found in GRCh38 and other reference genomes. This is due to a known issue with read realignment sporadically experiencing substantial slowdowns on very short, high-depth contigs. Until this issue can be resolved, runtime can be improved for such cases by excluding smaller contigs from analysis. This can be done in Strelka by creating a bed file of all the chromosomes that should be included in the analysis, and providing it as an argument to the call regions configuration option. 

So, can I restrict the variant calling process to an arbitrary subset of the genome by providing a region file in BED format with the --callRegions configuration option. I mean, I want to restrict to all the chromosomes, while excluding the small contigs and scaffolds in GRCh38 genome.

Besides, I find that some of the vcf output of Strelka2 is hard to understand, and strelka2 github is not active. Do you know whether Strelka2 still be maintained ? There are lots of issues on it's github, but no one reply them.

**Comment by gnarzisi** [comment]
As far as I know, Strelka2 is still actively supported. But this a question that should be posted on the Strelka2 GitHub repo, not here. 

In Lancet users can use the `--bed` option to restrict the variant calling process to an arbitrary subset of the genome.
