### ISSUE TITLE
Detailed tutorials

### ISSUE THREAD

**Issue by wangjiawen2013** [nygenome/lancet#48]
Dear,
There is a Basic usage of Lancet on this github,  a simple lancet command should look something like this:
lancet --tumor T.bam --normal N.bam --ref ref.fa --reg 22:1-51304566 --num-threads 8 > out.vcf

What if I have more than one tumor samples and normal samples ? Could give an example of the out.vcf and their explainations ?
Does Lancet support exome, RNA-seq and amplicon input ?

Looking forward more detailed document on Lancet.

**Comment by gnarzisi** [comment]
At this time only a single tumor-normal pair (either WGS or Exome) is supported. There is no direct support for RNA-seq and amplicon input.
