### ISSUE TITLE
Lancet gives errors when region file > 1000 lines

### ISSUE THREAD

**Issue by rpoulos** [nygenome/lancet#5]
Hi @gnarzisi,

I have been trying to run Lancet on a list of ~45,000 regions in the genome (totalling ~50 million nucleotides). However, I keep getting the following error message even though there appears to be no problem with the FASTA or FASTA index files:

> [fai_load] build FASTA index.
> [fai_build] fail to open the FASTA file GRCh37-lite.fa
> [fai_load] fail to open FASTA index.
> Could not load fai index of GRCh37-lite.fa
> Segmentation fault (core dumped)

I am using the following command:
`lancet -t TUMOR.bam -n NORMAL.bam -r GRCh37-lite.fa -B REGIONS.bed > output.vcf`

My regions are in BED format, such as the following:
1       31693   32941

The strange thing is that the error message disappears when I isolate the first 1000 lines of my input regions file and just run Lancet, with exactly the same input files, but instead with this smaller list of regions. Lancet appears to work perfectly with this smaller set of regions.

Is there an upper limit to the number of regions that Lancet can run on? Do you have any suggestions to overcome this issue?

Thanks for your help!

**Comment by gnarzisi** [comment]
This is a strange. 45,000 regions should not create a problem. Give the error that you get, the problem seems to be related to opening/loading the reference genome from the fasta file. 

I have not tested lancet on GRCh37-lite yet. Can you try using the regular GRCh37 reference genome fasta file? If the problem persists, please share with me your BED file and I can try to reproduce your error on my side.

**Comment by rpoulos** [comment]
Hi @gnarzisi,

Unfortunately I have now tried two additional reference files (Homo_sapiens.Ensembl.GRCh37.fa, HG19_Broad_variant.fa) but have had the same issue. 

Despite the contents of the error message, the problem appears to be with the length of the regions input file. For example, I get the same error as posted above when I run Lancet on a region file which contains 2000 regions (attached: Regions_2000.bed). However, when I break this file into two parts, Lancet runs without error on both the first 1000 lines of this file (attached: Regions_1000_pt1.txt) and on the second 1000 lines of this file (attached: Regions_1000_pt2.txt). 

Can you please see if you can reproduce the error on your side, and help me to resolve the issue?

Thanks!

[Regions_1000_pt1.txt](https://github.com/nygenome/lancet/files/888892/Regions_1000_pt1.txt)
[Regions_1000_pt2.txt](https://github.com/nygenome/lancet/files/888893/Regions_1000_pt2.txt)
[Regions_2000.txt](https://github.com/nygenome/lancet/files/888891/Regions_2000.txt)

**Comment by gnarzisi** [comment]
I was not able to reproduce your error.
I took the "Regions_2000.txt" bed that you posted and tested lancet on it using GRCh37 human genome. Everything worked fine for me (no FASTA index error) and a proper VCF file was generated.
I basically used the same command that you posted: 

lancet -t $T -n $N -r $REF -B $BED  > output.vcf

I still believe something is wrong with your FASTA index file. I have a few questions: 

-- Are you using the same reference fasta file that was used to align the reads in the bam files in the first place?
-- Have you tried reindexing the FASTA files? 
-- When you get the error, I assume it happens right at the beginning of the run. Correct?
-- Can you share the full output printed to standard error by the program?

**Comment by rpoulos** [comment]
Hi @gnarzisi,

I have worked out what the issue is, though I am not sure why you didn't face the same problem with my regions file. 

In the loadRefs function inside "Lancet.cc", the loaded fai file was not being destroyed at the end of each iteration of the loop. This meant that after a large numbers of regions (1017 regions, to be exact) had been loaded the tool fails as htslib doesn't seem to cope with multiple copies of the reference file being loaded. The issue can be corrected by inserting the following line into the script of Lancet.cc at line 243:
"fai_destroy(fai);"

Thanks for your correspondence on this issue,
Rebecca

**Comment by gnarzisi** [comment]
Thank you for sharing your fix. I have integrated it in the code. The problem maybe due to a different compiler version. In any case, glad that you found a solution.
