### ISSUE TITLE
Skipped windows

### ISSUE THREAD

**Issue by GeorgetteTanner** [nygenome/lancet#50]
Hi

I've been using Lancet to call variants from exome data and noticed the logs show a high number of skipped windows. Eg.:

 Total \# of skipped windows: 1755000 (88.5%)
  \# of windows with SNVs only: 171200
  \# of windows with indels only: 8200
  \# of windows with softclips only: 81
  \# of windows with indels or softclips: 8487
  \# of windows with SNVs or indels: 184279
  \# of windows with SNVs or softclips: 171685
  \# of windows with SNVs or indels or softclips: 185798

Am I right in thinking the skipped regions are just the non-exon regions due to lack of reads and therefore nothing to worry about?

(The data has been aligned with BWA and has the MD flags)

Thanks!

**Comment by gnarzisi** [comment]
Your are probably right if you run Lancet across the whole genome. But if you provided in input the BED file with the exome regions, then something may be off.

**Comment by GeorgetteTanner** [comment]
Thanks for confirming that. (I hadn't provided a BED file.)
