### ISSUE TITLE
WES bed file input

### ISSUE THREAD

**Issue by jennyp76** [nygenome/lancet#53]
Hi, 
I'm currently dealing with WES data which are expected to have a large amount of normal contamination (low tumor purity). When running lancet with --bed option, I got confused about which  bed file I have to use since Agilent offers 3 types of BED files(regions. covered, padded)

![image](https://user-images.githubusercontent.com/77954045/141060352-76f4df7c-ec23-442c-a4af-33399c4b9dce.png)

Could you give me a selection of the proper bed file?? 
Also, if you have any suggestions regarding low quality samples, please let me know. 
Thanks in advance

Jen

**Comment by gnarzisi** [comment]
Hi Jen,

you want to use the BED files that better represent the regions that have been actually covered by the probes, so the "Covered" BED file seems to be the most appropriate.
