### ISSUE TITLE
CRAM support

### ISSUE THREAD

**Issue by Rapsssito** [nygenome/lancet#56]
Are there plans to add CRAM support? `bamtools` does not have CRAM support (and it looks like it will never have [bamtools#149](https://github.com/pezmaster31/bamtools/issues/149)). Switching entirely to `htslib` will make the cut. However, it might take too much work.

**Comment by gnarzisi** [comment]
The current Lancet code depends heavily on bamtools, so CRAM support is not in the horizon for this implementation. However we have been working on refactoring the source code. The new version is planned to be released later this year and we'll feature several improvements including CRAM support. Stay tuned.
