### ISSUE TITLE
providing region doesn't work - output for whole-genome 

### ISSUE THREAD

**Issue by complexgenome** [nygenome/lancet#58]
Hi there,

I'm interested to run lancet for `CHR22` only. I provide bed file for whole-genome, but specify reg chr22. When I run, it runs for the whole-genome instead of just CHR22. BAM files are for whole-genome for tumor and normal.

Below is the command:

```
~/tools/lancet-1.0.7/lancet --tumor BM.tumor.ApplyBQSR.bam \
--normal BM_00.normal.ApplyBQSR.bam \
--ref GRCh38.primary_assembly.genome.fa \
--bed Twist_Exome_Target_hg38.padded.interval_list.bed --reg chr22 --num-threads 6 > CHR22_CLN_21141794_BM_00.lancet.vcf

```
I provided bed file for two reasons: 1) see if lancet simply picks CHR22, only, or otherwise. 2) I wanted to avoid making 22 bed files.

Let me know if any other details are needed.

**Comment by gnarzisi** [comment]
Thanks for reaching out. Unfortunately it is not possible to mix the --bed and --reg options in the current implementation. They can only be used one at the time. If you use them both, like in your command, the --bed options takes priority over the other. I am afraid that your only option at this time is to indeed create multiple bed files for each chromosome.

**Comment by complexgenome** [comment]
Thanks Giuseppe. 
It would be great to incorporate such feature in future release(s). 
I'd be interested to contribute if possible and if you've bandwidth.
