### ISSUE TITLE
Clarification of max-coverage parameters

### ISSUE THREAD

**Issue by edawson** [nygenome/lancet#6]
Hi,

I'm looking for clarification of the behavior triggered by `max-coverage-normal` and `max-coverage-tumor` parameters. Are windows exceeding the maximum coverage downsampled or just discarded?

Thanks,
    Eric

**Comment by gnarzisi** [comment]
Hi Eric,

`--max-coverage-normal` and `--max-coverage-tumor` are parameters only used to filter variants with extreme high coverage. To control which window to skip use:

`--max-avg-cov, -u         <int>         : maximum average coverage allowed per region [default: 10000]`

Windows with average coverage above this value are currently discarded. Downsampling is one of the features planned for the next release. Let me know if you have more questions.

**Comment by edawson** [comment]
Awesome, thanks @gnarzisi . Looking forward to having downsampling. The only other things is if you might have some scaling / performance numbers it would be nice to have them on the README. It took a bit of experimentation to know how much RAM/CPU usage to expect. Judging by the results it looks like it's affected by window size and not be region size.

**Comment by gnarzisi** [comment]
Thank for the suggestion Eric.
Can you share more about the experiments that you performed for tuning the performance? 
Curious on what values of the window size you have been experimenting with.

**Comment by edawson** [comment]
Sure thing - I'm running on a matched tumor normal set (Illumina 125bp reads, HiSeq X) at 40-60X normal / 80-100X tumor. I haven't run with different window sizes yet but I changed the region size from 1Mbp to 10Mbp and didn't see a huge bump in RAM usage, so I assumed it was dependent on a different parameter. I managed all but what looks like three genomic regions in <64GB of RAM.

I'm getting bogged down in a region on Chr10 of a lot of biological interest, but which has a lot of repeat elements (our coverage spikes to >10000). For what it's worth, we're still getting a 10Mbp region done in under 24 hours on a 32 thread cloud instance. I've since upped the RAM to 120GB and reduced `max-avg-cov` to 1000.

Are there any advantages to running a larger window size? I'm going to assume it limits the size of variants that can be detected unless you're stitching the graph tips together across windows.

**Comment by gnarzisi** [comment]
Lancet memory footprint is generally not significantly affected by the regions size (`--reg` parameter). Large regions are walked a long using the smaller window size. However, 120GB of RAM sounds quite a lot. Are you splitting by chromosomes?

Yes, a larger window size can help find larger variants. In general you should not have problems with window size up to 1kb, but we have not carefully tested larger sizes. In the limit, a too large window could be problematic to assemble if containing repeats and it could be discarded as a whole.

**Comment by edawson** [comment]
We're splitting each region to its own vm, so it sounds like we could reduce the amount of memory we give them.
