### ISSUE TITLE
Using lancet on tumor-only samples (without matched normal)

### ISSUE THREAD

**Issue by franmarpi** [nygenome/lancet#60]
Hello,
as I have read in the documentation, lancet is created to be used on **tumor/normal paired samples**. I was wondering if **would be possible to use it on tumor-only samples (without a matched normal)**.

I know that, in that case, it would be virtually impossible to tell somatic variants from germinal ones, but it might be interesting since it would be possible to use it on panel data.

Thanks in advance!

**Comment by gnarzisi** [comment]
Yes, you are correct that Lancet requires a matching (normal) sample. In the absence of that, you can provide the same sample twice. This is not a well tested or recommended mode of usage though. All the relevant variants would be labelled as "shared" in the output VCF.
