### ISSUE TITLE
A tip for mac users

### ISSUE THREAD

**Issue by proukakis** [nygenome/lancet#7]
I hope it's Ok to post an issue although I have actually solved it, in case it helps others.

basically, edit cmakelists.txt header adding extra make_policy line below, so it becomes:

# Cmake requirements
cmake_minimum_required( VERSION 2.6.4 )
**cmake_policy(SET CMP0042 OLD)**

Details

Using Mac OS X El Capitan. Was having problem with cmake of bamtools 

MACOSX_RPATH is not specified for the following targets:

BamTools

and bamtools appeared not to work

this is due to a change in cmake v3.0 and above 

``MACOSX_RPATH`` is enabled by default.

CMake 2.8.12 and newer has support for using ``@rpath`` in a target's install
name.  This was enabled by setting the target property
``MACOSX_RPATH``.  The ``@rpath`` in an install name is a more
flexible and powerful mechanism than ``@executable_path`` or ``@loader_path``
for locating shared libraries.

CMake 3.0 and later prefer this property to be ON by default.  Projects
wanting ``@rpath`` in a target's install name may remove any setting of
the ``INSTALL_NAME_DIR`` and ``CMAKE_INSTALL_NAME_DIR``
variables.

This policy was introduced in CMake version 3.0.  CMake version
3.9.3 warns when the policy is not set and uses OLD behavior.  Use
the cmake_policy command to set it to OLD or NEW explicitly.

.. note::
  The ``OLD`` behavior of a policy is
  ``deprecated by definition``
  and may be removed in a future version of CMake.

BTW- same problem / solution for scalpel

Thanks
christos

**Comment by gnarzisi** [comment]
Hi Christos, 

thank you so much for sharing your solution. It will definitely help others in the future. Most of lancet testing and development was performed under linux so I expected that some tuning was needed for Mac OSX users. In this cases however, it seems to be a CMake specific problem that could also affect linux users. In any case, I will include the extra make_policy in the bamtools "cmakelists.txt" file as default behavior for the Lancet distribution.
