### ISSUE TITLE
Run fails

### ISSUE THREAD

**Issue by jungminchoi** [nygenome/lancet#8]
I was trying to run Lancet on one of my WES samples and noticed that it immediately fails. Could you please look into this and offer help troubleshoot the issue? Before trying Lancet, somatic mutations were called by other algorithms without issues. 

Thanks so much,
Jungmin

```
[jc2545@c16n08 lancet]$ ~/programs/lancet/lancet --tumor ../X16-3406/X16-3406.bam --normal ../RPEM01/RPEM01.bam --ref /home/jc2545/ref_data/h_sapiens/1000genomes/2.5/b37/human_g1k_v37_decoy.fasta --bed /home/jc2545/ref_data/h_sapiens/intervals/hs37d5_MedExome_and_coding_padded_Nov2015.bed --num-threads 20 > pem01.vcf

Loaded 211193 from bedfile
288953 total windows to process

starting thread 1 on 36120 windows
starting thread 2 on 36119 windows
starting thread 3 on 36119 windows
starting thread 4 on 36119 windows
starting thread 5 on 36119 windows
starting thread 6 on 36119 windows
starting thread 7 on 36119 windows
starting thread 8 on 36119 windows
Process reads
/home/jc2545/programs/lancet/lancetProcess reads
/home/jc2545/programs/lancet/lancet: symbol lookup error: /home/jc2545/programs/lancet/lancet: undefined symbol: _ZN8BamTools9SamHeaderC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by gnarzisi** [comment]
Hi Jungmin, I am sorry you are having this issue. Never faced this problem before. However, it seems like this could be a compilation problem. Did you compile and run the code on the same machine (or different machines with the same configuration)? This blog post suggests a few ways to debug the problem: https://benohead.com/linux-c-lookup-error-undefined-symbol/

Please let me know if this helps you debugging and fixing the problem.

**Comment by jungminchoi** [comment]
Thank you! It turned out there was a problem in my environment and no issues with the build. 

A couple of questions.
1. Do you have any recommendations filtering out the potential FP variants other than selecting for "PASS" calls? We are mostly interested in microsatellite repeat calls Lancet detects.
2. Is there a way to check the artifacts due to OxoG using the output vcf file?

Thank you again for your time,
Jungmin

**Comment by gnarzisi** [comment]
Glad to hear that compilation worked fine.

The answer depends on the data. What type of data are you planning to run Lancet on? Whole-genome? Whole-exome? Other? For 80x/40x tumor/normal data lancet default filters should work just fine.
