### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by subject-am** [nygenome/lancet#9]
Hello,

I am having problems with building Lancet. I keep getting the same error (followed by others):
`Microassembler.hh:43:27: fatal error: api/BamReader.h: No such file or directory
compilation terminated.`
Since the file exists, at /src/api/BamReader.h, I was wondering if you could help me with this issue.

I'm attaching the Jupyter Notebook file, hoping it'll help in giving some insight.
Thanks in advance,
Ana M.
[install_lancet.pdf](https://github.com/nygenome/lancet/files/1351808/install_lancet.pdf)

**Comment by gnarzisi** [comment]
After inspecting your Notebook file, it seems that CMake is not installed in your system:

`/bin/sh: 1: cmake: not found`

Can you please install it and retry the compilation process?

**Comment by subject-am** [comment]
I thought it was included in the build essentials package, but apparently not.
Still I installed it, but I continue to being able to build it.
[install_lancet (1).pdf](https://github.com/nygenome/lancet/files/1362486/install_lancet.1.pdf)

**Comment by gnarzisi** [comment]
There seem to be no reported errors now, just warnings.
Are you sure that the "lancet" executable was not created in /home/subjectAM/lancet/src ?

**Comment by subject-am** [comment]
It was created there indeed:
![image](https://user-images.githubusercontent.com/31853642/31285947-90eb3f56-aab4-11e7-897f-c4afa0b388fb.png)

**Comment by gnarzisi** [comment]
Great! I'll close the ticket then.

**Comment by subject-am** [comment]
Thanks 👍
